DROP SEQUENCE SEQ_PRODUCTO;


DROP TABLE PRODUCTO CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_PRODUCTO
START WITH 1
INCREMENT BY 1;


/*CREATE TABLE PRODUCTO
(cod_producto  NUMBER(3) NOT NULL,
 nombre_producto VARCHAR2(50) NOT NULL,
 desc_producto VARCHAR2(400) NOT NULL,
 tasaint_producto NUMBER(4,2),
 nro_maximo_cuotas_prod NUMBER(3),
 CONSTRAINT PK_PRODUCTO PRIMARY KEY(cod_producto));
 
 CREATE TABLE REGION
(cod_region  NUMBER(3) NOT NULL,
 nombre_region VARCHAR2(50) NOT NULL,
 CONSTRAINT PK_REGION PRIMARY KEY(cod_region));  
 
 CREATE TABLE PROVINCIA
(cod_region  NUMBER(3) NOT NULL,
 cod_provincia NUMBER(3) NOT NULL,
 nombre_provincia VARCHAR2(50) NOT NULL,
 CONSTRAINT PK_PROVINCIA PRIMARY KEY(cod_region,cod_provincia),
 CONSTRAINT FK_PROVINCIA_REGION FOREIGN KEY(cod_region) REFERENCES REGION(cod_region)); 
 
 CREATE TABLE COMUNA
(cod_region  NUMBER(3) NOT NULL,
 cod_provincia NUMBER(3) NOT NULL,
 cod_comuna NUMBER(3) NOT NULL,
 nombre_comuna VARCHAR2(50) NOT NULL,
 CONSTRAINT PK_COMUNA PRIMARY KEY(cod_region,cod_provincia,cod_comuna),
 CONSTRAINT FK_COMUNA_PROVINCIA FOREIGN KEY(cod_region, cod_provincia) REFERENCES PROVINCIA(cod_region,cod_provincia)); 
 

 
 CREATE TABLE FORMA_PAGO
(cod_forma_pago   NUMBER(2) NOT NULL ,
 nombre_forma_pago VARCHAR2 (50) NOT NULL) ;
ALTER TABLE FORMA_PAGO ADD CONSTRAINT PK_FORMA_PAGO PRIMARY KEY (cod_forma_pago);
 */ 

 CREATE TABLE PERSONA (
	id_persona NUMBER(3) NOT NULL,
	nombre_persona
	apellido_persona
	apodo_persona
	fecha_nacimiento
	foto_persona
	id_nacionalidad
	
CONSTRAINT PK_PERSONA PRIMARY KEY(id_persona)); 
 
  CREATE TABLE USUARIO (
    id_persona NUMBER(3) NOT NULL,
	id_usuaruio NUMBER(3) NOT NULL,
	nombre_usuario VARCHAR2(150) NOT NULL,
	password
	direccion_usuario
	id_comuna
	mail_contacto
	
CONSTRAINT PK_USUARIO PRIMARY KEY(id_usuario)); 

 CREATE TABLE REGION
(id_region  NUMBER(3) NOT NULL,
 nombre_region VARCHAR2(50) NOT NULL,
 CONSTRAINT PK_REGION PRIMARY KEY(id_region));  
 
 CREATE TABLE PROVINCIA
(id_region  NUMBER(3) NOT NULL,
 id_provincia NUMBER(3) NOT NULL,
 nombre_provincia VARCHAR2(50) NOT NULL,
 CONSTRAINT PK_PROVINCIA PRIMARY KEY(id_region,id_provincia),
 CONSTRAINT FK_PROVINCIA_REGION FOREIGN KEY(id_region) REFERENCES REGION(id_region)); 
 
 CREATE TABLE COMUNA
(id_region  NUMBER(3) NOT NULL,
 id_provincia NUMBER(3) NOT NULL,
 id_comuna NUMBER(3) NOT NULL,
 nombre_comuna VARCHAR2(50) NOT NULL,
 CONSTRAINT PK_COMUNA PRIMARY KEY(id_region,id_provincia,id_comuna),
 CONSTRAINT FK_COMUNA_PROVINCIA FOREIGN KEY(id_region, id_provincia) REFERENCES PROVINCIA(id_region,id_provincia)); 
 
  
  
 CREATE TABLE CLIENTE
(numrun NUMBER(10) NOT NULL,
 dvrun VARCHAR2(1) NOT NULL,
 pnombre VARCHAR2(50) NOT NULL, 
 snombre VARCHAR2(50), 
 appaterno VARCHAR2(50) NOT NULL, 
 apmaterno VARCHAR2(50),
 foto BLOB,
 fecha_nacimiento DATE NOT NULL,
 fecha_inscripcion DATE NOT NULL,
 correo VARCHAR2(20),
 fono_contacto NUMBER(10),
 direccion VARCHAR2(50) NOT NULL,
 cod_region  NUMBER(3) NOT NULL,
 cod_provincia NUMBER(3) NOT NULL,
 cod_comuna NUMBER(3) NOT NULL,
 cod_prof_ofic  NUMBER(3) NOT NULL,
 cod_tipo_cliente  NUMBER(3) NOT NULL,
 CONSTRAINT PK_CLIENTE PRIMARY KEY(numrun),
 CONSTRAINT FK_CLIENTE_COMUNA FOREIGN KEY(cod_region, cod_provincia,cod_comuna) REFERENCES COMUNA(cod_region,cod_provincia,cod_comuna),
 CONSTRAINT FK_CLIENTE_PROFESION_OFICIO FOREIGN KEY(cod_prof_ofic) REFERENCES PROFESION_OFICIO(cod_prof_ofic),
 CONSTRAINT FK_CLIENTE_TIPO_CLIENTE FOREIGN KEY(cod_tipo_cliente) REFERENCES TIPO_CLIENTE(cod_tipo_cliente)); 



CREATE TABLE CUOTA_TRANSAC_TARJETA_CLIENTE
(nro_tarjeta NUMBER(30) NOT NULL,
 nro_transaccion NUMBER(10) NOT NULL,
 nro_cuota NUMBER(2) NOT NULL,
 fecha_venc_cuota DATE NOT NULL,
 valor_cuota NUMBER(10) NOT NULL,
CONSTRAINT PK_CUOTA_TRANS_TARJETA_CLIENTE PRIMARY KEY(nro_tarjeta, nro_transaccion,nro_cuota),
CONSTRAINT FK_TRANTARJ_TRAN_TARJ_CLIENTE FOREIGN KEY(nro_tarjeta,nro_transaccion) REFERENCES TRANSACCION_TARJETA_CLIENTE(nro_tarjeta,nro_transaccion));


CREATE TABLE PAGO_MENSUAL_TARJETA_CLIENTE
(nro_tarjeta NUMBER(30) NOT NULL,
 anno_mes_pago NUMBER(6) NOT NULL,
 fecha_vencimiento DATE NOT NULL,
 fecha_pago DATE NOT NULL,
 monto_total_pagar NUMBER(10) NOT NULL,
 monto_pagado NUMBER(10) NOT NULL,
 saldo_por_pagar NUMBER(10) NOT NULL,
 cod_forma_pago NUMBER(2),
CONSTRAINT PK_PAGO_MENSTARJ_CLIENTE PRIMARY KEY(nro_tarjeta,anno_mes_pago),
CONSTRAINT FK_PAGO_MENSTARJ_FORMA_PAGO FOREIGN KEY(cod_forma_pago) REFERENCES FORMA_PAGO(cod_forma_pago),
CONSTRAINT FK_PAGO_MENSTARJ_TARJETA FOREIGN KEY(nro_tarjeta) REFERENCES TARJETA_CLIENTE(nro_tarjeta));


 
INSERT INTO PRODUCTO VALUES(SEQ_PRODUCTO.NEXTVAL,'Tarjeta FalRip','Permite efectuar compras en cualquier tienda (física o virtual) que pertenece al Retail y en cualquier tienda adherida. Ademas permite solicitar Avances y Súper Avances de Dinero',NULL,NULL);

 
INSERT INTO TIPO_TRANSACCION_TARJETA VALUES(SEQ_TP_TRANSAC_TARJETA.NEXTVAL,'Compras Tiendas Retail o Asociadas',0.05,48,1);

INSERT INTO TIPO_CLIENTE VALUES(SEQ_TIPO_CLIENTE.NEXTVAL,'Trabajadores dependientes','De los útimos 3 meses');

INSERT INTO FORMA_PAGO VALUES(1,'Efectivo');
INSERT INTO FORMA_PAGO VALUES(2,'Transferencia Electrónica');
INSERT INTO FORMA_PAGO VALUES(3,'Cheque');

INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Tarapacá');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Antofagasta');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Atacama');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Coquimbo');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Valparaíso');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Del Libertador Gral. Bernardo O’Higgins');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Del Maule');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Del Biobío');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'De la Araucanía');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'De Los Lagos');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Aysén del Gral.Carlos Ibáñez del Campo');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'De Magallanes y de la Antártica Chilena');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Metropolitana de Santiago');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'De Los Ríos');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'Arica y Parinacota');
INSERT INTO REGION VALUES(SEQ_REGION.NEXTVAL, 'De Ñuble');

INSERT INTO PROVINCIA VALUES(1,1,'Iquique');
INSERT INTO PROVINCIA VALUES(1,2,'Tamarugal');
INSERT INTO PROVINCIA VALUES(2,1,'Antofagasta');
INSERT INTO PROVINCIA VALUES(2,2,'El Loa');
INSERT INTO PROVINCIA VALUES(2,3,'Tocopilla');
INSERT INTO PROVINCIA VALUES(3,1,'Copiapó');
INSERT INTO PROVINCIA VALUES(3,2,'Chañaral');
INSERT INTO PROVINCIA VALUES(3,3,'Huasco');
INSERT INTO PROVINCIA VALUES(4,1,'Elqui');
INSERT INTO PROVINCIA VALUES(4,2,'Choapa');
INSERT INTO PROVINCIA VALUES(4,3,'Limarí');
INSERT INTO PROVINCIA VALUES(5,1,'Valparaíso');
INSERT INTO PROVINCIA VALUES(5,2,'Isla de Pascua');
INSERT INTO PROVINCIA VALUES(5,3,'Los Andes');
INSERT INTO PROVINCIA VALUES(5,4,'Petorca');
INSERT INTO PROVINCIA VALUES(5,5,'Quillota');
INSERT INTO PROVINCIA VALUES(5,6,'San Antonio');
INSERT INTO PROVINCIA VALUES(5,7,'San Felipe de Aconcagua');
INSERT INTO PROVINCIA VALUES(5,8,'Marga Marga');
INSERT INTO PROVINCIA VALUES(6,1,'Cachapoal');
INSERT INTO PROVINCIA VALUES(6,2,'Cardenal Caro');
INSERT INTO PROVINCIA VALUES(6,3,'Colchagua');
INSERT INTO PROVINCIA VALUES(7,1,'Talca');
INSERT INTO PROVINCIA VALUES(7,2,'Cauquenes');
INSERT INTO PROVINCIA VALUES(7,3,'Curicó');
INSERT INTO PROVINCIA VALUES(7,4,'Linares');
INSERT INTO PROVINCIA VALUES(8,1,'Concepción');
INSERT INTO PROVINCIA VALUES(8,2,'Arauco');
INSERT INTO PROVINCIA VALUES(8,3,'Biobío');
INSERT INTO PROVINCIA VALUES(9,1,'Cautín');
INSERT INTO PROVINCIA VALUES(9,2,'Malleco');
INSERT INTO PROVINCIA VALUES(10,1,'Llanquihue');
INSERT INTO PROVINCIA VALUES(10,2,'Chiloé');
INSERT INTO PROVINCIA VALUES(10,3,'Osorno');
INSERT INTO PROVINCIA VALUES(10,4,'Palena');
INSERT INTO PROVINCIA VALUES(11,1,'Coihaique');
INSERT INTO PROVINCIA VALUES(11,2,'Aisén');
INSERT INTO PROVINCIA VALUES(11,3,'Capitán Prat');
INSERT INTO PROVINCIA VALUES(11,4,'General Carrera');
INSERT INTO PROVINCIA VALUES(12,1,'Magallanes');
INSERT INTO PROVINCIA VALUES(12,2,'Antártica Chilena');
INSERT INTO PROVINCIA VALUES(12,3,'Tierra del Fuego');
INSERT INTO PROVINCIA VALUES(12,4,'Última Esperanza');
INSERT INTO PROVINCIA VALUES(13,1,'Santiago');
INSERT INTO PROVINCIA VALUES(13,2,'Cordillera');
INSERT INTO PROVINCIA VALUES(13,3,'Chacabuco');
INSERT INTO PROVINCIA VALUES(13,4,'Maipo');
INSERT INTO PROVINCIA VALUES(13,5,'Melipilla');
INSERT INTO PROVINCIA VALUES(13,6,'Talagante');
INSERT INTO PROVINCIA VALUES(14,1,'Valdivia');
INSERT INTO PROVINCIA VALUES(14,2,'Ranco');
INSERT INTO PROVINCIA VALUES(15,1,'Arica');
INSERT INTO PROVINCIA VALUES(15,2,'Parinacota');
INSERT INTO PROVINCIA VALUES(15,4,'Tamarugal');
INSERT INTO PROVINCIA VALUES(16,1,'Diguillín');
INSERT INTO PROVINCIA VALUES(16,2,'Punilla');
INSERT INTO PROVINCIA VALUES(16,3,'Itata');

INSERT INTO COMUNA VALUES(1,1,1,'Iquique');
INSERT INTO COMUNA VALUES(1,1,2,'Alto Hospicio');
INSERT INTO COMUNA VALUES(1,2,1,'Pozo Almonte');
INSERT INTO COMUNA VALUES(1,2,2,'Camiña');
INSERT INTO COMUNA VALUES(1,2,3,'Colchane');
INSERT INTO COMUNA VALUES(1,2,4,'Huara');
INSERT INTO COMUNA VALUES(1,2,5,'Pica');
INSERT INTO COMUNA VALUES(2,1,1,'Antofagasta');
INSERT INTO COMUNA VALUES(2,1,2,'Mejillones');
INSERT INTO COMUNA VALUES(2,1,3,'Sierra Gorda');
INSERT INTO COMUNA VALUES(2,1,4,'Taltal');
INSERT INTO COMUNA VALUES(2,2,1,'Calama');
INSERT INTO COMUNA VALUES(2,2,2,'Ollagüe');
INSERT INTO COMUNA VALUES(2,2,3,'San Pedro de Atacama');
INSERT INTO COMUNA VALUES(2,3,1,'Tocopilla');
INSERT INTO COMUNA VALUES(2,3,2,'María Elena');
INSERT INTO COMUNA VALUES(3,1,1,'Copiapó');
INSERT INTO COMUNA VALUES(3,1,2,'Caldera');
INSERT INTO COMUNA VALUES(3,1,3,'Tierra Amarilla');
INSERT INTO COMUNA VALUES(3,2,1,'Chañaral');
INSERT INTO COMUNA VALUES(3,2,3,'Diego de Almagro');
INSERT INTO COMUNA VALUES(3,3,1,'Vallenar');
INSERT INTO COMUNA VALUES(3,3,2,'Alto del Carmen');
INSERT INTO COMUNA VALUES(3,3,3,'Freirina');
INSERT INTO COMUNA VALUES(3,3,4,'Huasco');
INSERT INTO COMUNA VALUES(4,1,1,'La Serena');
INSERT INTO COMUNA VALUES(4,1,2,'Coquimbo');
INSERT INTO COMUNA VALUES(4,1,3,'Andacollo');
INSERT INTO COMUNA VALUES(4,1,4,'La Higuera');
INSERT INTO COMUNA VALUES(4,1,5,'Paiguano');
INSERT INTO COMUNA VALUES(4,1,6,'Vicuña');
INSERT INTO COMUNA VALUES(4,2,1,'Illapel');
INSERT INTO COMUNA VALUES(4,2,2,'Canela');
INSERT INTO COMUNA VALUES(4,2,3,'Los Vilos');
INSERT INTO COMUNA VALUES(4,2,4,'Salamanca');
INSERT INTO COMUNA VALUES(4,3,1,'Ovalle');
INSERT INTO COMUNA VALUES(4,3,2,'Combarbalá');
INSERT INTO COMUNA VALUES(4,3,3,'Monte Patria');
INSERT INTO COMUNA VALUES(4,3,4,'Punitaqui');
INSERT INTO COMUNA VALUES(4,3,5,'Río Hurtado');
INSERT INTO COMUNA VALUES(5,1,1,'Valparaíso');
INSERT INTO COMUNA VALUES(5,1,2,'Casablanca');
INSERT INTO COMUNA VALUES(5,1,3,'Concón');
INSERT INTO COMUNA VALUES(5,1,4,'Juan Fernández');
INSERT INTO COMUNA VALUES(5,1,5,'Puchuncaví');
INSERT INTO COMUNA VALUES(5,1,6,'Quintero');
INSERT INTO COMUNA VALUES(5,1,7,'Viña del Mar');
INSERT INTO COMUNA VALUES(5,2,1,'Isla de Pascua');
INSERT INTO COMUNA VALUES(5,3,1,'Los Andes');
INSERT INTO COMUNA VALUES(5,3,2,'Calle Larga');
INSERT INTO COMUNA VALUES(5,3,3,'Rinconada');
INSERT INTO COMUNA VALUES(5,3,4,'San Esteban');
INSERT INTO COMUNA VALUES(5,4,1,'La Ligua');
INSERT INTO COMUNA VALUES(5,4,2,'Cabildo');
INSERT INTO COMUNA VALUES(5,4,3,'Papudo');
INSERT INTO COMUNA VALUES(5,4,4,'Petorca');
INSERT INTO COMUNA VALUES(5,4,5,'Zapallar');
INSERT INTO COMUNA VALUES(5,5,1,'Quillota');
INSERT INTO COMUNA VALUES(5,5,2,'Calera');
INSERT INTO COMUNA VALUES(5,5,3,'Hijuelas');
INSERT INTO COMUNA VALUES(5,5,4,'La Cruz');
INSERT INTO COMUNA VALUES(5,5,5,'Nogales');
INSERT INTO COMUNA VALUES(5,6,1,'San Antonio');
INSERT INTO COMUNA VALUES(5,6,2,'Algarrobo');
INSERT INTO COMUNA VALUES(5,6,3,'Cartagena');
INSERT INTO COMUNA VALUES(5,6,4,'El Quisco');
INSERT INTO COMUNA VALUES(5,6,5,'El Tabo');
INSERT INTO COMUNA VALUES(5,6,6,'Santo Domingo');
INSERT INTO COMUNA VALUES(5,7,1,'San Felipe');
INSERT INTO COMUNA VALUES(5,7,2,'Catemu');
INSERT INTO COMUNA VALUES(5,7,3,'Llaillay');
INSERT INTO COMUNA VALUES(5,7,4,'Panquehue');
INSERT INTO COMUNA VALUES(5,7,5,'Putaendo');
INSERT INTO COMUNA VALUES(5,7,6,'Santa María');
INSERT INTO COMUNA VALUES(5,8,1,'Quilpué');
INSERT INTO COMUNA VALUES(5,8,2,'Limache');
INSERT INTO COMUNA VALUES(5,8,3,'Olmué');
INSERT INTO COMUNA VALUES(5,8,4,'Villa Alemana');
INSERT INTO COMUNA VALUES(6,1,1,'Rancagua');
INSERT INTO COMUNA VALUES(7,1,1,'Talca');
INSERT INTO COMUNA VALUES(7,2,1,'Cauquenes');
INSERT INTO COMUNA VALUES(7,3,1,'Curicó');
INSERT INTO COMUNA VALUES(7,4,1,'Linares');
INSERT INTO COMUNA VALUES(8,1,1,'Concepción');
INSERT INTO COMUNA VALUES(8,2,1,'Lebu');
INSERT INTO COMUNA VALUES(8,3,1,'Los Ángeles');
INSERT INTO COMUNA VALUES(9,1,1,'Temuco');
INSERT INTO COMUNA VALUES(10,1,1,'Puerto Montt');
INSERT INTO COMUNA VALUES(10,1,9,'Puerto Varas');
INSERT INTO COMUNA VALUES(10,2,1,'Castro');
INSERT INTO COMUNA VALUES(10,3,1,'Osorno');
INSERT INTO COMUNA VALUES(11,1,1,'Coihaique');
INSERT INTO COMUNA VALUES(11,2,1,'Aisén');
INSERT INTO COMUNA VALUES(12,1,1,'Punta Arenas');
INSERT INTO COMUNA VALUES(13,1,1,'Santiago');
INSERT INTO COMUNA VALUES(13,1,14,'Las Condes');
INSERT INTO COMUNA VALUES(13,1,32,'Vitacura');
INSERT INTO COMUNA VALUES(13,2,1,'Puente Alto');
INSERT INTO COMUNA VALUES(13,3,1,'Colina');
INSERT INTO COMUNA VALUES(13,4,1,'San Bernardo');
INSERT INTO COMUNA VALUES(13,5,1,'Melipilla');
INSERT INTO COMUNA VALUES(13,6,1,'Talagante');
INSERT INTO COMUNA VALUES(14,1,1,'Valdivia');
INSERT INTO COMUNA VALUES(14,2,1,'La Unión');
INSERT INTO COMUNA VALUES(15,1,1,'Arica');
INSERT INTO COMUNA VALUES(16,1,1,'Chillán');

INSERT INTO PROFESION_OFICIO VALUES(SEQ_PROFESION_OFICIO.NEXTVAL,'Abogado');


INSERT INTO CLIENTE VALUES('8333032','5','RODOLFO ','SERGIO','FRITZ','OTAROLA',EMPTY_BLOB(),'14/11/1953','19/09/1993',null,null,'Errázuriz 234 Depto 45 Edificio Vista Mar','5','1','1','2','20');


INSERT INTO TARJETA_CLIENTE VALUES('32924617341','24617341','19/12/2013','20','1660000','1162000','498000','464800');
COMMIT;
